### ISSUE TITLE
Use HTTP.rb instead of HTTParty

### ISSUE THREAD

**Issue by rye** [frc-frecon/frecon#107]
I ran into a few problems when I was bulk-importing over HTTP using the Scraper class from my various test databases. I ran some benchmarks and noticed that it was not using the network card anywhere near what it should if it was using the raw Net::HTTP layer or actual raw sockets.

[httprb/http](/httprb/http) is a pretty neat library that would allow us to do HTTP a lot faster and more cleanly. It has a nearly-identical API to that of HTTParty, but is native and thus faster.  It's also leaner, and much more actively-maintained by its maintainers.

So I think I will migrate us away from HTTParty.  Since it's only used for the Scraper, it'll be a trivial change, especially since the module just needs to get renamed.  This Issue just serves as a bit of documentation, but comments are welcome.

**Comment by Sammidysam** [comment]
:+1:
