### ISSUE TITLE
Protect branch 'master'

### ISSUE THREAD

**Issue by rye** [frc-frecon/frecon#79]
This is mainly a question for @Sammidysam: would it be okay with you if I were to lock the `master` branch down so that GitHub will (a) disable force pushing, (b) prevent it from being deleted, and, perhaps most attractively (c) require status checks before merging?  Each of these make sense, and I can only see there being a problem if you try to force-push.  Status checks will help to push us to use Travis for the stuff.

**Comment by rye** [comment]
I went ahead and did this. We can revert back and unprotect it later if you would like.

**Comment by Sammidysam** [comment]
That sounds good to me.  Force pushing is very rarely needed is you really screw up, but I hope none of us will screw up that badly in the future. :)

**Comment by rye** [comment]
That's the idea.  I can only see this feasibly interfering with force-pushing a rebase or amendment, and both of those situations are edge cases we don't really need to worry about.
